kind: Secret
ansible_user: ENC[AES256_GCM,data:L2duzfo/Mg==,iv:PSVtQs5DvDHoj+LyVN+EPCNuFxL09wXKfVZAO/8Sj94=,tag:s/ZAkphC5A8ccBBDFdp99g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NQrxbRfOm/fIOav4QYkcvlCErdA6,iv:/uZgrnnK1tKPMVpMOYMhRCZVN1Shi0aRVowvoXuEDUo=,tag:+1oYYFHL7Qq+j8ZZZgffqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197yv04vfaqasrgnz9mkdrgjg2e3z0g0f45rcjam3gr4uz02vysmqw40g25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ3pVYjB1MHVrZ0huYnkr
            bDlUUmFpbXBKcFRuSzArbkZ6Z2F6QitxZGpzCnhqQkIrL3dOaFJlSUxZQ0R4TG5E
            VjlNNkovQ0Myc3ZhcEZ4bi9wNEE1UDQKLS0tIGhHQTRDdkxndVlZQVJBM1VTVHQ3
            S25MK2tRY2xpSzZ2VldMdmtGdEVhUXcKHnwYYpr5Mwkon60mjU1ocQJ8h+IpDDmH
            X9oZ/XoUm8R0mM0zJmKwDL4oqYgqfJY2+Pl5UhuX/AQjWLD6ambKUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-15T02:40:54Z"
    mac: ENC[AES256_GCM,data:AQ0qWUtFIyTW8xqFdDpevJs+vxRQl+twSsYBHe+wPftnS11hb4xo/M2lQYOtuy2o9iYeOuNvfUmOUJest8bbAfuD/gRrOJBJ9zK94fliuqw39eDLR/gt3zIuiNUCUTRZbGL0iLUnM8W+L7uxxSc2b8zsMXdGXlW3QXf33oD6FKY=,iv:R5Ol+pxr69zmr3RHTpX6Je/AsecTLu1cp+j/N7sBvb4=,tag:L1drf7lCadmnzvj9TCyjxQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
