kind: Secret
ansible_user: ENC[AES256_GCM,data:jexo40pZeg==,iv:jra6MgUuQVFw5a/cOGNvv3D/LELcOUczMfgid6bBslo=,tag:mI7tMlVe8eXOtPmMW2tW4Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5Hb3LEjFJss5KRUx2J9J0GJ1RIU=,iv:dC5kn0V0jQdehpeHmE1HYE5yfKVjxW8yEbC3Zp/a/xM=,tag:UgFEZbCzqOcBulJ0AnbYaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbDRZSWRJOEFkdkgzMXp1
            Zzk3WlI3TTNpY1F2YXdRUG1hcEZFZkl5UTAwCmllYmZ3cXFxc2JaVjNqQU93SWwr
            T1FyZGUyMkU3ZTU0S3dwaEszd0lzS2cKLS0tIGI3YTBSYkN1R2ZsMys5ZTdRK3ZB
            bWlQWjUrWkJWUTBuZTF4T05iWG9SeVUKK6QvTNQc8b3vAFreSG16kclDhY9vZX40
            LaVCSNb3NaSeX1OVCBzSjDGh+NJkgIiPYo+pY8KxkcjMTkY+aELyFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-20T04:32:47Z"
    mac: ENC[AES256_GCM,data:4UXXO/FkITAK463k0WX+WYnbb2J5cj5jQNBiJiUfu+qhQD/sHGfeQV1TlC8N8IWv07eUR0tAQaFCDCpqAroG7nbu3549exJz660KrfpTAr9jg+fyzfc1s0f9CfBL4MJyM0GS3yjmN3Hpi8e2Br+OjiBRMCdVpBFbt/ConckZh8I=,iv:mGAHH2tEK98ekcKro3PCa2zJmIgy4dBRMRmQgkaDmsM=,tag:SWesZhfUW1LE45Aqy3g0qA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
