kind: Secret
ansible_user: ENC[AES256_GCM,data:dpgWyMuOIQ==,iv:6EmGojdU4Pvbr2x30qiU3k1xufxYI6gygYbEp09Gewg=,tag:3rUj/BfCFmwk63rkJVqdUg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OH5M0EL/3AXt/k63VLXi65kU16iT,iv:OZkJB+hCXLt3DM+GvGlQfEpv/nVJ3S6HSqjfjPPIQ7c=,tag:q/o+UdAMkAoHW+cY89ur2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYUp3cStHNWlpRlJzUlhx
            Z2hqQ2R4UFZRbDI1WndYcGNlWGwwM2F2dUZRCmNnN1EyN1BCV1FBL1VuL2I1YnFL
            a2gyK1E3OEpKL3NxRnpQMmF0ZHBIVjQKLS0tIDdwVnZIb3RYY2ZhQmQ5WjVoT0g0
            UjBRbWlKVjRVZ2ZDMVd6endFUUwzRWcKbJ9cUc8Q5fY0Gb0rqtnTxSyhy53yubjK
            PfVTKRoAn4vabxrSIQ6bOujoVsSkP84hNuENAAEZKc78UH16x/jRhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T00:14:39Z"
    mac: ENC[AES256_GCM,data:shsz3AqBfgZzbLbRVFmESS5AlbeNm6LjLBfib05Rs+Up9G7CxDygPGEyH9Cz5YhE4tV2EffaKpHDHzs5Tb0RpRgjGbpKzU/5893XgejkGXgjdPlnST3rCVWLW3/IgS38mPo2wXbyl65+FTNgp+1AU4ZKoFVgeuhQBObGQEaO2eY=,iv:e4f8VpsUPrBRg/irVMxO9yBTczDF+FX3Cq+c4lToRdA=,tag:n6FMbgfTSKsJwHD3Nn7k5g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
