kind: Secret
ansible_user: ENC[AES256_GCM,data:o/yIV78HSg==,iv:XWXaxrfv3kHgSqw9Ydua8bmJiKZcuJNVj35+r/ug6ek=,tag:XNqV+jMdR5gUSF2FJ76LVg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8QbHpxPfutcldi6wkdYftmh0ojw=,iv:nM74E4wc9uGas7UYekgBin/yHeSoQVAe3cK/4OnKFfU=,tag:+OIXJoH2i14mx1xHvLDZJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbnJheS9BZXJYdlJCd054
            ZlBvRTZOYzkxYlNGQnluc3RIMWlXNnNwMWg0CjhTZXNTYnN5NVpuOG5xV1FWaEo3
            WFpRQjU2TDFkQXJUQmp2dVpGcjg2VFEKLS0tIEdSZXJZWTFCVnJsVjl6ZlpoSncr
            UUw0aDNoQysyVEFuREZEWHVPdDdUOTgKH5X5EihBg1ycW9kxI5YYgcTcRRi+fzYR
            Vvk5H6kvyW8yDqnKccyHTV9JJ0/GbExdKTLXquvgak7UsJJj/QYiWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-20T04:32:47Z"
    mac: ENC[AES256_GCM,data:2hS9uOPkicOmvFY3eZgJTQX5F3VKYWxJCtqTUJmEXpGc/wwrUFUQg71xJuTFTmwsfcA4RmjSamlVddwv7ghf4RFny0QIzjjPCFjuHmD+pGli2PTkg4mSV42rZmulWWcZVHqKvS6BKkYoLsr9s8gmkPoyhFxJ6apAXUtdH52GBcY=,iv:FEtWJp3OkIQ6azcmzWBMN0A2xwFKc+3k2ki6m83TGac=,tag:YF87Gi79kjia5VlQnwHtQw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
