kind: Secret
ansible_user: ENC[AES256_GCM,data:ej0b4p4gtg==,iv:EyIxiVd0/lAVzg7VV96GWFyNSeuV/03dzUwsh6ruzZ4=,tag:JalayNr8lCAeL9qamnNfXA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ougFoxfZsb8gKYROtEDQXJB1oTnD,iv:Tfol9un05WsNXG824kj/0uG8x/2tafZwnseBgA+LEqI=,tag:H524SSZdv5haSEiLueN0tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197yv04vfaqasrgnz9mkdrgjg2e3z0g0f45rcjam3gr4uz02vysmqw40g25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUWExakpwVHZnMHZDSUlz
            dDVwWHRPVmtNVk5BekhIMVNJZmZidnZUdFg0CnFEa3Exejl1SUZiVGw1M2R4NVFr
            NC9TcERndUFCaGo1ZU9nYlpHSUJWVUUKLS0tIHpCbEJhdHRkWE4vcUxrRCt4QVJG
            aUsrN2M0bDJXTVQ2cUU1Z3ZoNjlJS3MKzazNE4K9BQDm62hL4tcLkMp/+vagbhvy
            RU5x8Nn2dY9x5cL+b4pBIStVWrGwn1isNi4CAnDJ9K/RSahaQGfArw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-14T04:41:46Z"
    mac: ENC[AES256_GCM,data:brMZHPgBnHWUV432tix+0BO4B8vS0+O9mgjQBkULGD7HtRORuoGAdk6HNP1x1VGRdJO23Maqqz+pkQtAe5kC9oHxpNSTfwthNpC5e6DSEq/eHBPPT0Ho52FFWd7/OnnoihhWwKFj5Rbv6W0cghElW8GSSIq8LD2e5cfgQr5Yh+M=,iv:sliJFmH/trdyiZf9Na51JUqsUmwtn+oAMR3CYzGdsR0=,tag:PXjk+sWzxPetr+YKdzhFag==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
