kind: Secret
ansible_user: ENC[AES256_GCM,data:8CuBX/rMvw==,iv:15kmlitPX7/zTX2fnFlh9IWFcjHfzhLcqrAW3SFskFQ=,tag:lkW1P70gbCal1UD6b1SRmQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OwSqTQK2ICME3GVrQkwYkMTgEeE=,iv:KSksulfJStK3r3/T+Ljh0TXS+cb7xdPaYreWZFuj3ag=,tag:x9A9NMhRZGcGXE8b4sbJ2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeSt5VzB0U3hSOHdYQTMy
            OE5Hcmo1TWdpT0h3bHhseTljd05Fb0NLQ25rClFjbnFyWE50RUdMM3ZUVjE2M3pI
            djY5d1pNOW5YelV4ck44dFdobktpb3cKLS0tIHNDSmFONEZSazJUZk01Y0pOMURG
            WTlWdFhIaGhjYVcyYVhaVnZLTGVHY3cK1SwYtleT1gdWITGndy1pFsqToALK3oP/
            mzIyHiDJr1ufYMTL/sbv0Gl1Aq1XxXi3fEOHgZl+yAxa47py9+gU6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-15T13:46:47Z"
    mac: ENC[AES256_GCM,data:zso34wR5YNrL73mG7zUgH/t6+l1q/gB7IH6HY+PepzoQSxq0LIuFrrPOelmaTjgKFoHVyyS4wyIUdcEVacrZbYcOhbgQkOzZQf2QxOfcLvI//SaM5JSqyVakbYc2N84Zz/PutEr8zJ7f1dFbuTJMI4E1Vg+MlSrG9se/F+8ERkc=,iv:vYI6aSC2CwuGKHRwys9576qllXq/iUkGkxyY60F0p2k=,tag:IzG9qN5XYegSGaoCXbpdxw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
