kind: Secret
ansible_user: ENC[AES256_GCM,data:+a4S5UbDOQ==,iv:VMNGLTXz+5CpDV8BJMICNhK/Q63PNgADlML1Kl4GNe4=,tag:JmJzrrmKN8Wa30cNmoZX8g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HJVMWKrfEkLVFY1n+M5B7iichCk=,iv:TiNQSgai56rrzLf5qompICUzuYvEyqhmWQNzLdTzHFo=,tag:oQS6A8CZ+uhrW/GDjo24QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYVY1YzhCZXVRckhyaWNu
            VHJaKy8vamNsUFNXVUtMT1dMaWR3NERBeG5NCmk5RHhOc2M2V1FIZWF0QzZXNER1
            RjlnTndrZkpxZ2hCV0MzSTFIZUx0c1EKLS0tIHlIcDdqNGY1cWN0emYxMnk4MWdv
            Z1JOSnpkY2dVdW9DQzRuRE1GUmxVem8KEsu8jPUeffsbGD8XNe7fdibvlGScb42n
            lrL6yWQQ21JeJLTgzRspHI/RiXcMF85P5NqS/ksok1rkbFZdSUZecg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-20T04:32:47Z"
    mac: ENC[AES256_GCM,data:gtgcccBuEk7v+6fZVUCPcXWkg/KZuP1xIzMU9OwS/To9IxgP/hP8zLZKVCuQpoZiPeax1ocex2GUGo7n/eJ0xEq3Ob0nib2ZSj4HOdG6GgSBItyzvOkD4fUK7FHZ295Y7SvW0mLov/RyYcsCGcd2N1hRmfq/3st32GzOG8DQhwE=,iv:J5UCNetlyjP2QJrj68ERI7/B3/wj9O509i7tHnPdj1w=,tag:03vatnhqD/P3dhgVxDY/SA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
