kind: Secret
ansible_user: ENC[AES256_GCM,data:VFj2oOT0ow==,iv:+8anF0pOCtlraA/R1GeTnomwAFstzepdd5lDUDPZA/U=,tag:w2rkaaJvM2IivDqr7U4sdQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:3j1VR9tYTj4aNW01PDv25L+v56I=,iv:ubhLwD9gmogj2+j+QnnLXFWFKXR/sPOn50n2eKAqnL8=,tag:XkyGUc8HXjR7hCGblpyAMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWk1yaTVHMGp6QnRkTzRF
            dTFsSjcycmZaR1NoM0RuZEVtY29UTkwwTVQwCnA3TFpXbmNFSHZuNnRYU05IOUtS
            c0g4ZHVyTjVRKzV5c2MxMnpLcDYvUUUKLS0tIFhBMXp3UDI5Vy9tNXptNER3M3ZH
            dTh3SEp3ZFU0T1pEaGUvSXVZM0swclEKeIsgZnt9TQR6/95or8OD8Fr+MkMzqzcP
            H0TZaUu+eMU43zEjYcCq8zpXIpcE4MpXE/JP17ZmxBfYQYhYKfrN/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-16T08:07:38Z"
    mac: ENC[AES256_GCM,data:ZkOX7o9FG+g2x2uZdZe7ZTSCTF0GQUtghqrjhLl4FLwIPsCUqOwd5wjqrmBkzCbFn4/pjcy1TKO4Ga/eIjJhO0LS5ktG7jt2Zd0jkeWCImkjjrIgf+MMvUaYQvhpow0zF0Rv3ecSEGM1a/dTE5cAqQBZQ41VbXvg66XlkzydiBA=,iv:F6H2jo4uJ04CK2Zz9xxqrAM79u2Rx3GxEBH/6Briy3U=,tag:WT4+5yK+itqyiWpFCl6WCA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
