kind: Secret
ansible_user: ENC[AES256_GCM,data:RNwN+jeHOA==,iv:oUB0VvZ0QRa/B1+Xg6mKo+u9PtuEN17S7ptqQnS4p+8=,tag:V53oVXhVwoIC74Px6f4xbA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:bzve/D+EjEEfkYFtKqrabktBKwgS,iv:VXT60JPdQOEUR4/sk+FNPt/skZ5NyiQHLgWpm9tslMg=,tag:Bb5iQ8Pl3c2tT9nLm6wBjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197yv04vfaqasrgnz9mkdrgjg2e3z0g0f45rcjam3gr4uz02vysmqw40g25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYzdVd0JJcFBBSFh1KzEx
            NmtNRENTTjVXN2g4c2pJWHZsRjlRWEV6Nm5zClRWdkhTTHhSQW1hVzBBNkxwNzk2
            NUt1N1R0eVBQcGJRc1lyWjUwalluSDAKLS0tIG1RcThUdjdyVUE4N1FuWXI4YnlQ
            bGN4RlZrUEVpVVo2VURYMENzZDUrcWMKSQgFKRTHcaTHV4KLJP5Sv0roN45ba36T
            LjumhLrLr52v2AdIrgvkFh3Wqmp0rVLx/HYImJW7p7XQvw3AAlDlfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-14T04:41:46Z"
    mac: ENC[AES256_GCM,data:qcGhvOXUB5pPk2eRv8EB562Q6QukviA04tEgZKXDrzYMti0d02mb9vgH7cLSCujjwvNPzuSryJZZzfyCHIj7vL6M5AvBEESyVyysE0+guyefz7fBzIvT5S45mvIOYHfZnPtBvQBbLRRjomaVOp5YK6+LodnGOC2nmndSKd9JOAM=,iv:B99ZIs0kW+BXCCa7fWH8aMclBSLFUBPFbDN19awY19U=,tag:CG2JABzBNy6kFTWotswwHA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
