# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D9IMd5knlQqvNME5bw==,iv:S8EI522VDJYZg5jMHh7/o0/8GZ9AVrxBUP/iLp+Fkrs=,tag:oft7jMYTwU2Uv8aYd7kH1Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vEa1V1ziWAm1iL5UQhwidkjq,iv:4Ozu92IzLWI14+FUidTP46xOxvZhWpXLnPHPKl66UXc=,tag:b3+7dsl30U3QpynWjDDHAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197yv04vfaqasrgnz9mkdrgjg2e3z0g0f45rcjam3gr4uz02vysmqw40g25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTzd6b3p0WmhYYmMyZUlO
            N1Z5Mk9aMkJSYjJ0MjZLNmNtMkttZzlpV1dRCnZBMCs3aGlOMzNXM2lXaWpyeUdr
            RmRUYitmd0tTTS9wanJITGxQOTA2OHcKLS0tIFdSWkx2YWtZVDk0QTVRYnNma1Bi
            aUQxd2U2VFZnVW9iWmtucjVKVjc1TGMKd7MbPZGFnEmJxwtiNW/QdCgkNkrSZy/8
            x+ry6MyRx+AjLIiYLi1tZmSoi9dkYf3k6Sdm9FChQQb5n8fZeyqfFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-14T04:41:46Z"
    mac: ENC[AES256_GCM,data:cPzu6PFGIBH+/06Eazm0aNvgd4wkHkNQYorA6zZFX8Aqiv1WgY0DuFrePCEkWp1KQXGEkEUMT32Fw+2l/D6Po1atYwatFQFkW3eq42W6aUbzDyaC1/wLRuV2njuSfjkFz1KVYprHtxH9RP48lutB88xMu5/LtWTCAEAwnDIIx5I=,iv:riAvNK/mndJUxQkLXsxUpj7asj+A/vGIA74Tqx1gTYE=,tag:nltrK8taYHNpUHyuc4NodQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
