# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XION51AM1M45kXV2Qw==,iv:xg3vutHHUNyCFgTqHSf/WIOw2cDVwByjsSv0e4wLmmY=,tag:iPiQGfrFnzC0uvc735rkpg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:D2L4plRLOANeiCh+DMLtrZUC,iv:FRuuPa2sg1qzyUvw3rrg5+9RmhMh8w4JbPhgVP1hNzo=,tag:w+wfs4NgOJD12xFpyC9L7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197yv04vfaqasrgnz9mkdrgjg2e3z0g0f45rcjam3gr4uz02vysmqw40g25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVlIvcDkrTjZscUFOVEs3
            N0svU2VZWG5CaGZ1VUh5MkFtRHFuTk0yRzJJCkRCQWNNNTNDcHpvSHl2bVlDL2Yz
            aFUvYjZqa3NoWFBXakZSdHZDaUZ0Qk0KLS0tIHdiNVZVOEFGVnFrQXhIRjEyUEV6
            emVDYzVEYXBVNDBIOFBxclBhQk9XRzgKeRne9tYOC6ASLnV/XTHla8LRYG9ktnnV
            XjiPBj08OWCvWkuskgW/JfGYp/xAskovwbu0O8+kHag0CPnpK/eIlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-15T02:40:54Z"
    mac: ENC[AES256_GCM,data:gBt3t5GtcRRFcSfpP5rQyUv1N0ZVcN2qY/7afF/QHX+TfL4VCT4R+uhqJ8Fg5bZFMgP0VbsXGFjb8irE2cLZUYascGJRx2qW6Wcfk8YOvGoG1VYp9wHxpAXOgxOFLbO4RTRGpsQjDkbSunbw8B2zMQvfnmsnYDQy4dJEhGaXoOM=,iv:L6G3WoWR+V7V59RUeWY/m9Mg7dM7JVnreqDjPEzZ+Vc=,tag:G8FXCPrCjFhlO7YDqZX99A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
