# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hi1V6H4h/btwauvq+A==,iv:GZWCF2WoDuuz+KeuBpmuzeSdx3crMtBFmylUDBNQQTQ=,tag:6PvtTinP1/ZQXGwPEcKVpQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:n0sSJ6qATt6yKs5P64fSX8zw,iv:bpBn2IC0GxyTmxb98ynjo2zI3O5LWolzJh0ZghE+hGQ=,tag:k65Wj/vQAU/FowErF01xUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Qlk3QVdVVSt2elRuSzMx
            L3dHVHdhWDV1L21MbG9GSGJrSU5NUldoM3dNCjV2OTY3cnljQzdnZ0tQRUlMcWVK
            V0J5UW9USXdoVVVZeTJpb0ltZUJ4OTgKLS0tIFZMRWFBRzRpTitrT1ZkU2J0T2J1
            TE82T1lubnJLNllOMDlqYm1od2s5OWcKO9a0Stf5IhkqMHFg6/O8Cd9429RGtqDo
            kbbwNxIQXmhAVr8lJCeK7i5G9ZMMTz9wkR8zhuFsCg29VXCENPbAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T04:20:10Z"
    mac: ENC[AES256_GCM,data:VSSmum4v2J/Fa92O/vpILjiTkRxfBmrUeQt43HxlfqNyYkylNE0n4LuBLhR9FFY9gbuOnvgzF0fxqB9NnDee7hH7rvxsFUt1kpIoDddM4hdezqVjP44HjHSzgDqNwgkzrveGEeZBTvLoZGROTfylvJfOzsRcPuUX1B3ptV3owGQ=,iv:ltSS5nd5fXb33sjW/JGUDQI2hjMl2jTjsANkH63brlk=,tag:d6fyJY6vUvyYQo2yC8aWOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
