# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Kry7Odf6px3hUITfJBS9KeSbJ0iZjbTCJskc4ZlnYO4eFP8YSA==,iv:UtQkbb2aU5Nl+TdqNVixgkMglrfkLW5oZazMWG1+0XY=,tag:2HV5r8WuL/gPsEgKOLvU/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-10T05:18:49Z"
    mac: ENC[AES256_GCM,data:dC19n+wGNbHTgc/0wy9sBNJAzYngr8uFBLhvJSHov5cIXGrx0tXH11XFiDTe+0Slq1/dIg1qXYAPbVkC4PfijfmeQ/DK2uV5yKfmqULZ5YiYub2pf16Tvzi+NqJQslBF3hBSnA0tkDehrkBM9/3RXKHew5HZWkgrUXhnJMZWBDw=,iv:EgEPEcp7zhGf6CYuIN+VgFecD9EVp+PFdV1wsuMFOYU=,tag:T75psE92sYsVcsuBezsiuQ==,type:str]
    pgp:
        - created_at: "2022-01-10T05:18:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1TSbYMqplnVAQ/+I1TKc3FfUFwqWO3bLnavJIiX3f0FR/lUwR7vhTXwCK4H
            FFBPyW2bHzibmTsm6urGdpzHgDUMkG1CyryNy3fJXFwMyhk+jkP4L/kksi1/7443
            QX6gDOabh2/HX4gimcHTkWV/WbTHkb4wWwp6P4zQ0OcOchvuIO+vjGKazimMgjLc
            tEutlnu6XYNWVVIxK42xvGc1LnThyylWysCTRwLbyj1BdCY8v7iKqNJFh+42Ht3w
            mf2wcYM1lWn18YeXmjm0sbxy7j4dlRCgJs/HRoq8aGLsXRl+D7pn3PDI7pKuh8Sd
            oaaXkuKZUgkdBi6oX0PwbWjxYJaFr3F/Qo5vb9bOwG2rqLmOf2lZQCO0veMd/AG8
            w0DgDAI2V11i56dJAbc8tHmYwqG4VPlXzy+QuDY36DT8FiaP7D9/FxOZ5vIqMtU3
            zt36TQGPpmClXT32oBMLJWQbukDeYEirmuMekZSX3++nnE2mKsMFfzEk/MXD0FFK
            wnUc+dCBYsbabSrHt0wYmr9EE0cGhnInc97gEDtO8hgZZLzz97maZfxFP96kUW7E
            2qyIGfFQ0Mbcu3HURbfDu9ylX10Pe/poRfsCSijSD2UsZv49aTBsPqimQ4TikGI4
            EBP6ubZloyURaKYXvcCh5aTgqn1wIXrb+Wah7wMYZo3ttBdvPv1UUK2cuPCzvPHS
            XgG4XQdT/HeTBOROstJiWZkdnq+t4WfJzezCZAmzkwK3USr5QXoO1p2lHkR2tK3f
            sGwkiAOBHvWJg8YlycNfr+V9eGK5ZOaYaG5dsoCMDnZxD2kyI0zogjJhtMh4EYg=
            =kR7Q
            -----END PGP MESSAGE-----
          fp: 1000D340F411BA949FCE8462F7FED56A5B41AA83
        - created_at: "2022-01-10T05:18:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3rG3J2nz4Q3AQ//fzpIjBS+VGUssovJX+t24Nt595hdTolfJsMbtt4/dwdc
            K35tRxyzPQ2EuDtVGstxa0bc2m4II4TmU91ejnxYPh3OwXNyQee74wgMglqN+628
            rQu8o9So9haw63Q65AyR4I5XMROl4CjQOSBs7kbtyOvoSuOXlhW9ZEqBw7PnfrjL
            Z/D+aoktsnDqqhX9mgeYjy08ck6Ztk3/ltvfqece7+9DL3v6qVDjjmAxLhp/w+da
            bs9bz82HDRRAASmPBht9eA09pvhe3+5khGPbrpXTyS9F2IMAG5puloRslOMunp54
            Vc2IY6VKYB9JjiOu30gKmUsJ4PzgOMSp5NE02rVwTDrAz7PwTdgY8cDOT/33u65c
            HHLDj1OK3xiCw6DwJQmGEKyIt+sMIRTd7QTSTcmLUUYZTzqxeS1Xrmp265qN9tNt
            NEY1Yi21N3NMYhe9YXVYKGFVWovLFuGnVsIpO4tYtk/JEZdx4cIv1D2CHasUYOd8
            x3GR7Wo4veGkOO2ShDWv89BNd3i9YumNy0pVjFn7EqWdpzV5F3zLHg7I31wKPSW0
            3KpPI23I8kBGHsctfuvoLQ/YoDJW7Ds3Q49qAWIgnaUrJTtSqui5B089OAZCiWwY
            Fpab5joWPK5WLJLSVF4GWTb9fl0+pq6EE4dKQlkG5lzuvnuYw/TLPZRkEh6OgXrS
            XgFqhT6PFjGWA8CtxB9kpEj8YfARrjw2vLt/bneZRD7NzuYw9eZznR7ydlpoWNip
            U1Yq0XwI37CsNiePMCkfkeZGV+eYGH4jRZmxMdwbiR/tajNKw3T2Yw4RZQsKNXA=
            =CMyj
            -----END PGP MESSAGE-----
          fp: D0F64E9CCCB2F49B31FDC712A5EF5F90ABD04151
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
