# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:YTv/tS3AvNfpTupXiiWElphjYg65YEM12iRN1w05rEcrWfsBSA==,iv:hrEaakLd2D5q8Yr6Kf6WIxjmo040HJ6SRtU4bwNJHCM=,tag:X8WEXhDJNRSBX1ZxNeIU3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c2tzSHZWdG5BZWlvMVlm
            WDVhYWNaMitNY3hPUTdUa2JxZHBrQmxUSndvCmZ5M0VqNTZGajJZekRua2Z2SXVW
            QUU3UWd1WGtwK3FtOE9FN0k1MjBzZU0KLS0tIFJ5eFVZM1ZZaTRSYnRMNXUyckgz
            QldLWjFWOW1oTmEvSzlDU1VtOXNIRFUKoIKAYVUQnrkYYdTgGEkCQXt7eHE6C2Ub
            yzJkNqw687nYqZlNoQcXP1Li9EyBFNnKsWmL9f3HKxQHkljNfLQqbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T00:14:39Z"
    mac: ENC[AES256_GCM,data:LoAB0YDty0c9GzqAay1PlpIsvs8Q2vcDCmB22daA53YbvlhZwrJDEom2CZxxfMibDNYTNSJEM5JVyC3qzB2NVYzolAFeKea5MkbqCXaGqwNZ8yS/hcjdpXpcbozwiY6zCcy+oVkdlq4tpipIK0PTcRcGWpBLen0XahKSRBrscL8=,iv:BDvjjyrIYK4RMk6JIGApGgSBd0D1uzeUpj+O9VDwGWA=,tag:ZtrwxtOfhmUvhs4GYX7FTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
