# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:w5u8nioWiWxWR8p+dhNl0HTzmh+kvjMcao8KwjDHLt7yc9tOkQ==,iv:siIhxtOAVZHeLVSToUTf08fz4B671m2DseJ5aUPWPCE=,tag:PZU8aqqF6vwk8mqAfmILBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h56pf573hsjggjwz03nxfnaf2zzy0n6j03dyyr9szknl5mzygks32vzxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTamhRdjBYYVBINHJUQWUy
            MGhXcFlwWWluYnpXRjQyWjFUb3R3RFJQcFY0CnRzaWpPWkNyRHBZdmk4Y2duSzcx
            ZTdYTTl1T3ZnaUE5b0R4LzJDeUVXK1UKLS0tIDJkb1lDZzVxN1cwallxTXlvODhh
            cTc1bGdhOUYxRU1BTzBmY24vMmVNejQKNZQt4zd2L+wcvV5lMCMolfDCpsc1S5w8
            aC9tOWVAhNx6W3lm4lI5ahhf2aYVsjpfkQ8q+99lSehmrDk8BYQXKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T07:20:41Z"
    mac: ENC[AES256_GCM,data:UVFsMNCR4QSgwdL1PSz+Nv+hWjmqynxxFqaFOi7l07f2pJHxoMsnCIvSnGxJNxmP6mO99ggSZbLBnw4+ojxtnmAyP1ijMaDJ4q8ImKnedknjoKeMJL8Itpcigqx+LdUPpoPyv6hE65tPxbWOniTkKRkmjer16Da+VqrHs6LXAQU=,iv:aehUbTVZ7sJjA+BvxyZL6TyUWhAyENh72/d3nhwyBpA=,tag:FySFWS/1XDOQ09HH7XT1XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
